### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by xdTAGCLAN** [silvanohirtie/Discord-Token-Generator#21]
When i do "py generator.py" it says:
Traceback (most recent call last):
  File "C:\Users\......\Downloads\Discord-Token-Generator-master\generator.py", line 5, in <module>
    import proxygen
  File "C:\Users\......\Downloads\Discord-Token-Generator-master\proxygen.py", line 1, in <module>
    from lxml.html import fromstring
ModuleNotFoundError: No module named 'lxml'

**Comment by Bozo9** [comment]
> When i do "py generator.py" it says:
> Traceback (most recent call last):
> File "C:\Users......\Downloads\Discord-Token-Generator-master\generator.py", line 5, in 
> import proxygen
> File "C:\Users......\Downloads\Discord-Token-Generator-master\proxygen.py", line 1, in 
> from lxml.html import fromstring
> ModuleNotFoundError: No module named 'lxml'

same

**Comment by pkoelin0** [comment]
do "pip install lxml" :P

**Comment by ThunderwareIncorprated** [comment]
> do "pip install lxml" :P

where lmao

**Comment by BasToTheMax** [comment]
I got the same, but for the requests module

**Comment by ghost** [comment]
> > do "pip install lxml" :P
> 
> where lmao

If you can't do it by default on the command line, I would recommend re-installing python3 with the PATH variable added (On windows). If that's not an option, it's probably somewhere near the python executable. Look for pip.py, I think.

**Comment by silvanohirtie** [comment]
Hi Guys, the issue is that you're missing the lxml python's module. 
Just a little tip: Before trying to create a big project like this, learn first how a determinate language works.
https://learnpython.org
